### ISSUE TITLE
"Game freaks out"/"spins forever" using 360 guitars, even with HidHide enabled

### ISSUE THREAD

**Issue by InvoxiPlayGames** [InvoxiPlayGames/FestivalInstrumentMapper#65]
I think I've narrowed down the issue of the automatic HidHide configuration being broken to people with Fortnite installed to drives that aren't their C drive, or any other case where drive letter -> drive volume mapping would be weird.

A temporary workaround would be to open a Command Prompt, then use the HidHideCLI tool to add Fortnite directly:
```
cd C:\Program Files\Nefarius Software Solutions\HidHide\x64
HidHideCLI.exe app-reg "D:\Games\Fortnite\FortniteGame\Binaries\Win64\FortniteClient-Win64-Shipping.exe"
```
where you'd replace "D:\Games\Fortnite" with the path of your Fortnite game install folder.

**Comment by InvoxiPlayGames** [comment]
Also, if you've updated Windows since installing HidHide, you might have to uninstall and re-install it.

**Comment by DigitalxGoon** [comment]
I'm gonna give this a shot, if it doesn't work I'll try uninstalling Fortnite and reinstalling to the same drive the Epic Games launcher is in, as I know some games just freak out when their launcher is on a different drive (couple years working at Ubisoft taught me that).

**Comment by InvoxiPlayGames** [comment]
> 'HidHideCLI.exe' is not recognized as an internal or external command,

Did you run the "cd" command before it? And is Command Prompt showing that as the folder you're in? (type C: to switch drive letters in command prompt, if your cmd window is in another drive)

**Comment by Charlster** [comment]
This worked for me! Thanks so much :) Do you know if we'll have to do this each time we boot or can we now just start mapping without touching controller hiding every boot of the game?

**Comment by InvoxiPlayGames** [comment]
>Do you know if we'll have to do this each time we boot or can we now just start mapping without touching controller hiding every boot of the game?

If the game's on an internal hard drive/SSD and you use the same USB port for your controller/dongle, it *should* stay the same across reboots. There's an option in the tool to refresh the HidHide blacklist of controllers if you switch USB port or it changes for some reason.

**Comment by jaronlucas** [comment]
I did everything here and it still doesn't work. :/

**Comment by jaronlucas** [comment]
It will recognize my controller, but even with this fix, it spins. I tried refreshing the blacklist, everything.

**Comment by DigitalxGoon** [comment]
> I did everything here and it still doesn't work. :/

When you copied the command above, Did you replace the section in quotations with your own file path?

**Comment by jaronlucas** [comment]
> When you copied the command above, Did you replace the section in quotations with your own file path?
I did.

**Comment by jaronlucas** [comment]
Do I need to do fortnite.exe rather than the fortniteclient?

**Comment by jaronlucas** [comment]
I'm getting this message.


C:\Program Files\Nefarius Software Solutions\HidHide\x64>HidHideCLI.exe app-reg "C:\Program Files\Epic Games\Fortnite\FortniteGame\Binaries\Win64\FortniteClient-Win64-Shipping.exe"
Error code 0x0005 at src\FilterDriverProxy.cpp(33) `anonymous-namespace'::Device: Access is denied.

**Comment by jaronlucas** [comment]
> I'm getting this message.
> 
> 
> 
> 
> 
> C:\Program Files\Nefarius Software Solutions\HidHide\x64>HidHideCLI.exe app-reg "C:\Program Files\Epic Games\Fortnite\FortniteGame\Binaries\Win64\FortniteClient-Win64-Shipping.exe"
> 
> Error code 0x0005 at src\FilterDriverProxy.cpp(33) `anonymous-namespace'::Device: Access is denied.
> 
> 

Actually I figured that part out. The hidhide client was open. But now, I mapped my controller and clicked hide on the program, but it is not recognizing the controller in game period.

**Comment by DigitalxGoon** [comment]
> I'm getting this message.
> 
> C:\Program Files\Nefarius Software Solutions\HidHide\x64>HidHideCLI.exe app-reg "C:\Program Files\Epic Games\Fortnite\FortniteGame\Binaries\Win64\FortniteClient-Win64-Shipping.exe" Error code 0x0005 at src\FilterDriverProxy.cpp(33) `anonymous-namespace'::Device: Access is denied.

I searched the error message at the end of the message you're seeing and it appears to be an error produced directly from HidHide, try opening HidHide and see any other devices that HidHide may be accessing and then try disconnecting them until you figure out which one is causing the issue, then try the steps again to stop the spinning issue in Fortnite.

**Comment by jaronlucas** [comment]
> I searched the error message at the end of the message you're seeing and it appears to be an error produced directly from HidHide, try opening HidHide and see any other devices that HidHide may be accessing and then try disconnecting them until you figure out which one is causing the issue, then try the steps again to stop the spinning issue in Fortnite.

It ended up being because hidhide was open in the background. I closed it and it fixed that issue. But now I have another issue. When I hide my controller, I go in game, and it doesn't recognize my controller at all. The inputs from the controller won't do anything and the pro mode does not show. Even after I did that command.

**Comment by fruet** [comment]
I fixed the issue without using HidHide. I'm using the Guitar Hero 5 guitar wireless with the usb wireless receiver.
What I did: I opened x360ce and created a virtual controller, turned on my guitar after that, opened FestivalInstrumentMapper and selected the option with (2) in the end, closed x360ce. Double imputs gone and no more spinning.

**Comment by DigitalxGoon** [comment]
> > I searched the error message at the end of the message you're seeing and it appears to be an error produced directly from HidHide, try opening HidHide and see any other devices that HidHide may be accessing and then try disconnecting them until you figure out which one is causing the issue, then try the steps again to stop the spinning issue in Fortnite.
> 
> It ended up being because hidhide was open in the background. I closed it and it fixed that issue. But now I have another issue. When I hide/map my controller, I go in game, and it doesn't recognize my controller at all. The inputs from the controller won't do anything and the pro mode does not show. Even after I did that command.

I am not sure how to resolve that issue, but this is what I do every time I plan on playing Festival.

1. Open Mapper
2. Map Controller
3. Launch Fortnite
4. Hit a button or strum to see if the controller is registered
5. Do **NOT** use the keyboard and controller simultaneously, Mapper does not like this, though it is easily corrected by just hitting a button on the controller to "reset"

**NOTE: In the game settings themselves, I have _my_ controller set to "Custom" under presets and the controller platform set to Generic _(though HidHide should force this setting on its own)._ Give that a shot as well.**

If you're seeing that you're still having issues, I have no idea if this will work or not but would try restarting your PC, and start from a fresh boot. If you're still having issues you could try uninstalling the remapper, hidhide, restart your PC and then reinstall them and try again. Make sure HidHide is not accessing any other devices as well.

**Comment by jaronlucas** [comment]
> > > I searched the error message at the end of the message you're seeing and it appears to be an error produced directly from HidHide, try opening HidHide and see any other devices that HidHide may be accessing and then try disconnecting them until you figure out which one is causing the issue, then try the steps again to stop the spinning issue in Fortnite.

> 
> 
> 
> I am not sure how to resolve that issue, but this is what I do every time I plan on playing Festival.
> 
> 
> 
> 1. Open Mapper
> 
> 2. Map Controller
> 
> 3. Launch Fortnite
> 
> 4. Hit a button or strum to see if the controller is registered
> 
> 5. Do **NOT** use the keyboard and controller simultaneously, Mapper does not like this, though it is easily corrected by just hitting a button on the controller to "reset"
> 
> 
> 
> **NOTE: In the game settings themselves, I have _my_ controller set to "Custom" under presets and the controller platform set to Generic _(though HidHide should force this setting on its own)._ Give that a shot as well.**
> 
> 
> 
> If you're seeing that you're still having issues, I have no idea if this will work or not but would try restarting your PC, and start from a fresh boot. If you're still having issues you could try uninstalling the remapper, hidhide, restart your PC and then reinstall them and try again. Make sure HidHide is not accessing any other devices as well.

I tried all of that and still to no avail. But I appreciate the detailed response with all the troubleshooting. I tried the custom setting and everything and it just does not work. I've had festival work once with my controller and santroller and then I rebooted my computer and it just stopped working. I didn't do anything different. There must be some setting in a program that changed. I'm not sure.

**Comment by Believeinsteve92** [comment]
> I fixed the issue without using HidHide. I'm using the Guitar Hero 5 guitar wireless with the usb wireless receiver. What I did: I opened x360ce and created a virtual controller, turned on my guitar after that, opened FestivalInstrumentMapper and selected the option with (2) in the end, closed x360ce. Double inputs gone and no more spinning.

Did you setup the virtual controller in any specific way? Such as mapping with the guitar at all? I'm not too familiar with x360ce but I'm not seeing a way to set the controller as a guitar somehow

**Comment by Believeinsteve92** [comment]
I've tried moving my fortnite install to c:\ to no luck. I've also tried what I believe is the x360ce fix above but without more details I can't confirm. Still having the same issue with rockband wireless guitar where it spins constantly and doesn't seem to recognize as rb4 guitar with hidhide off. If hidhide is on, then no input works with the guitar in fortnite.

**Comment by fruet** [comment]
> > I fixed the issue without using HidHide. I'm using the Guitar Hero 5 guitar wireless with the usb wireless receiver. What I did: I opened x360ce and created a virtual controller, turned on my guitar after that, opened FestivalInstrumentMapper and selected the option with (2) in the end, closed x360ce. Double inputs gone and no more spinning.
> 
> Did you setup the virtual controller in any specific way? Such as mapping with the guitar at all? I'm not too familiar with x360ce but I'm not seeing a way to set the controller as a guitar somehow

I only did Options > Virtual Device > Install > Controller 1 > Add > Enable 1 Mapped Device > Save all

**Comment by jaronlucas** [comment]
> > > I fixed the issue without using HidHide. I'm using the Guitar Hero 5 guitar wireless with the usb wireless receiver. What I did: I opened x360ce and created a virtual controller, turned on my guitar after that, opened FestivalInstrumentMapper and selected the option with (2) in the end, closed x360ce. Double inputs gone and no more spinning.
> 
> > 
> 
> > Did you setup the virtual controller in any specific way? Such as mapping with the guitar at all? I'm not too familiar with x360ce but I'm not seeing a way to set the controller as a guitar somehow
> 
> 
> 
> I only did Options > Virtual Device > Install > Controller 1 > Add > Enable 1 Mapped Device > Save all

Yeah man that unfortunately didn't work. It's not clear whether you keep x360ce open when you go into Fortnite and then close it and then remap your other controller?

**Comment by fruet** [comment]
> > > > I fixed the issue without using HidHide. I'm using the Guitar Hero 5 guitar wireless with the usb wireless receiver. What I did: I opened x360ce and created a virtual controller, turned on my guitar after that, opened FestivalInstrumentMapper and selected the option with (2) in the end, closed x360ce. Double inputs gone and no more spinning.
> > 
> > 
> > > 
> > 
> > 
> > > Did you setup the virtual controller in any specific way? Such as mapping with the guitar at all? I'm not too familiar with x360ce but I'm not seeing a way to set the controller as a guitar somehow
> > 
> > 
> > I only did Options > Virtual Device > Install > Controller 1 > Add > Enable 1 Mapped Device > Save all
> 
> Yeah man that unfortunately didn't work. It's not clear whether you keep x360ce open when you go into Fortnite and then close it and then remap your other controller?

Yeah, I close it and the controller works just fine into Fortnite. I'm using the new version of x360ce (4.17.15.0) if that helps. In resume, that's my step by step setup every time I want to play:

Open x360ce (makes windows noise that controller is connected) > Turn on my controller > Open FestivalInstrumentMapper and select the option with (2) in the end > Start Mapping in FestivalInstrumentMapper > Close x360ce (makes windows noise that controller is disconnected) > Open Fortnite

**Comment by Sharemess** [comment]
> cd C:\Program Files\Nefarius Software Solutions\HidHide\x64
> HidHideCLI.exe

This worked exactly the way you said, thank you a LOT

**Comment by jaronlucas** [comment]
After troubleshooting pretty much all day. From what I can determine, all the mapping is doing for me is hiding my controller. It's not actually tricking it to be a rock band controller. It worked once, but after a reboot, it didn't again. I don't know what the reboot would have changed. I've tried doing x360ce, the command process, refreshing my blacklist, among other things like reinstalling both programs.

**Comment by Believeinsteve92** [comment]
> > > > > I fixed the issue without using HidHide. I'm using the Guitar Hero 5 guitar wireless with the usb wireless receiver. What I did: I opened x360ce and created a virtual controller, turned on my guitar after that, opened FestivalInstrumentMapper and selected the option with (2) in the end, closed x360ce. Double inputs gone and no more spinning.
> > > 
> > > 
> > > > 
> > > 
> > > 
> > > > Did you setup the virtual controller in any specific way? Such as mapping with the guitar at all? I'm not too familiar with x360ce but I'm not seeing a way to set the controller as a guitar somehow
> > > 
> > > 
> > > I only did Options > Virtual Device > Install > Controller 1 > Add > Enable 1 Mapped Device > Save all
> > 
> > 
> > Yeah man that unfortunately didn't work. It's not clear whether you keep x360ce open when you go into Fortnite and then close it and then remap your other controller?
> 
> Yeah, I close it and the controller works just fine into Fortnite. I'm using the new version of x360ce (4.17.15.0) if that helps. In resume, that's my step by step setup every time I want to play:
> 
> 1. **Open x360ce** (makes Windows noise that controller is connected)
> 2. **Turn on my controller** (makes Windows noise that controller is connected)
> 3. **Open FestivalInstrumentMapper** and select the option with (2) in the end
> 4. **Start Mapping** in FestivalInstrumentMapper
> 5. **Close x360ce** (makes windows noise that controller is disconnected)
> 6. **Open Fortnite**

It seems like the issue is that the guitar is showing up as player two with the x360ce method. if its player 1 it can control just fine. I don't really know how to get around that. I tried this and no luck unfortunately.

**Comment by Believeinsteve92** [comment]
Update. I was able to get my wireless RB2 guitar working with a third party receiver. Its important to know the change I think that made the difference for me was the driver I used for wireless receiver. I don't know how others got their drivers installed but I'll explain how I had to do mine.

Open device manager, go to Xbox 360 Peripherals, and then Xbox 360 wireless receiver for windows (might say something else for you). Right click, properties, click driver tab, then update driver. Click browse my computer for drivers, then let me pick from a list of available drivers on my computer. Here is where I went wrong. Make sure "Show compatible hardware" checkbox is checked. Mine then only has one option, "Xbox 360 wireless receiver for windows. If you have anything else, it didn't seem to work for me. For context, I was using rb4.app to use this same guitar through an adapter on roll limitless website to have it talk to my xbox through my pc. It will say "This driver is not digitally signed!" but thats okay. 

Once you reboot your pc, turn on remapper and good to go. Another thing to note is I was using fortnite on "D" drive but moved it to C drive after hearing about this. I also mapped it in HidHide manually myself just in case. Hopefully this helps some.

**Comment by Believeinsteve92** [comment]
> Update. I was able to get my wireless RB2 guitar working with a third party receiver. Its important to know the change I think that made the difference for me was the driver I used for wireless receiver. I don't know how others got their drivers installed but I'll explain how I had to do mine.
> 
> Open device manager, go to Xbox 360 Peripherals, and then Xbox 360 wireless receiver for windows (might say something else for you). Right click, properties, click driver tab, then update driver. Click browse my computer for drivers, then let me pick from a list of available drivers on my computer. Here is where I went wrong. Make sure "Show compatible hardware" checkbox is checked. Mine then only has one option, "Xbox 360 wireless receiver for windows. If you have anything else, it didn't seem to work for me. For context, I was using rb4.app to use this same guitar through an adapter on roll limitless website to have it talk to my xbox through my pc. It will say "This driver is not digitally signed!" but thats okay.
> 
> Once you reboot your pc, turn on remapper and good to go. Another thing to note is I was using fortnite on "D" drive but moved it to C drive after hearing about this. I also mapped it in HidHide manually myself just in case. Hopefully this helps some.

My own fix isn't even working for me. I had to do some pc maintenance and after that it no longer worked. Same OS, same files, only changes I made was I moved fortnite to a different drive without thinking, then after remembering I moved it back. Verified hidhide still had the same mapped location. Tried wireless receiver in a few different usb ports it would've been plugged into.

**Comment by Believeinsteve92** [comment]
Well idk what exactly did it but I plugged it back in its original usb port, then uninstalled the device, restarted pc, installed a different driver (more up to date one), restarted pc, then reinstalled the driver that worked in the past and it seemed to be fine.

**Comment by Pocokocska** [comment]
Hello i have this problem too.

I installed mapper and my character is automatically moving.

I did not install a seperate hidhider and i dont have the hidhide program on c drive.

Do i need something more?

My game is located at 

"D:\Fortnite\Fortnite\FortniteGame\Binaries\Win64\FortniteClient-Win64-Shipping.exe"

i am trying to use command

cd C:\Program Files\Nefarius Software Solutions\HidHide\x64
HidHideCLI.exe app-reg "D:\Fortnite\Fortnite\FortniteGame\Binaries\Win64\FortniteClient-Win64-Shipping.exe"

Im getting error message says not found the path and hidhidecli.exe is not recognized as an internal or external command.

Thank you for your help!

**Comment by RealGrootKicker** [comment]
For those still having issues: if you have Steam open, it will often try to interpret your controller as well for games (even if they are not from steam), which adds another area of input. Closing completely out of steam can fix this issue.
